### PR TITLE
Enable gradle enterprise

### PR DESCRIPTION
**Pull request by atomfrede**
Regenerated with gradle enterprise enabled. For CI/CD to work we must set a secret. It seems I don't have access on the main repository to do that.

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
in private, plz send to me the key + secret and I'll put it

**Comment by pascalgrimaud** [comment]
Just added GRADLE_ENTERPRISE_ACCESS_KEY secret

**Comment by atomfrede** [comment]
Thanks. Will merge it, let's see if the build appears in our gradle enterprise instance.

**Comment by atomfrede** [comment]
:facepalm: I can't merge it. Can you do it?

**Comment by pascalgrimaud** [comment]
@atomfrede : just invited you as admin of this repo

**Comment by pascalgrimaud** [comment]
is it ok ? everything works fine ?

**Comment by atomfrede** [comment]
Yes! All works fine, we can see now if the behaviour has changed between releases https://ge.jhipster.tech/scans?search.relativeStartTime=P7D&search.timeZoneId=Europe/Berlin

**Pull request merged**
